# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "db/cache_schema.rb"
    - "db/queue_schema.rb"
    - "db/cable_schema.rb"
    - "bin/**/*"
    - "gems/**/*"
    - "specifications/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "config/initializers/devise.rb"

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - "config/routes.rb"
    - "test/**/*"
    - "db/seeds.rb"
